// Map of countries to their corresponding country flag emoji codes and country codes
const countryFlags: Record<string, { flag: string; code: string }> = {
  Afghanistan: { flag: "🇦🇫", code: "AF" },
  Albania: { flag: "🇦🇱", code: "AL" },
  Algeria: { flag: "🇩🇿", code: "DZ" },
  "American Samoa": { flag: "🇦🇸", code: "AS" },
  Andorra: { flag: "🇦🇩", code: "AD" },
  Angola: { flag: "🇦🇴", code: "AO" },
  Anguilla: { flag: "🇦🇮", code: "AI" },
  Antarctica: { flag: "🇦🇶", code: "AQ" },
  "Antigua and Barbuda": { flag: "🇦🇬", code: "AG" },
  Argentina: { flag: "🇦🇷", code: "AR" },
  Armenia: { flag: "🇦🇲", code: "AM" },
  Aruba: { flag: "🇦🇼", code: "AW" },
  Australia: { flag: "🇦🇺", code: "AU" },
  Austria: { flag: "🇦🇹", code: "AT" },
  Azerbaijan: { flag: "🇦🇿", code: "AZ" },
  Bahamas: { flag: "🇧🇸", code: "BS" },
  Bahrain: { flag: "🇧🇭", code: "BH" },
  Bangladesh: { flag: "🇧🇩", code: "BD" },
  Barbados: { flag: "🇧🇧", code: "BB" },
  Belarus: { flag: "🇧🇾", code: "BY" },
  Belgium: { flag: "🇧🇪", code: "BE" },
  Belize: { flag: "🇧🇿", code: "BZ" },
  Benin: { flag: "🇧🇯", code: "BJ" },
  Bermuda: { flag: "🇧🇲", code: "BM" },
  Bhutan: { flag: "🇧🇹", code: "BT" },
  Bolivia: { flag: "🇧🇴", code: "BO" },
  "Bosnia and Herzegovina": { flag: "🇧🇦", code: "BA" },
  Botswana: { flag: "🇧🇼", code: "BW" },
  Brazil: { flag: "🇧🇷", code: "BR" },
  "British Indian Ocean Territory": { flag: "🇮🇴", code: "IO" },
  Brunei: { flag: "🇧🇳", code: "BN" },
  Bulgaria: { flag: "🇧🇬", code: "BG" },
  "Burkina Faso": { flag: "🇧🇫", code: "BF" },
  Burundi: { flag: "🇧🇮", code: "BI" },
  Cambodia: { flag: "🇰🇭", code: "KH" },
  Cameroon: { flag: "🇨🇲", code: "CM" },
  Canada: { flag: "🇨🇦", code: "CA" },
  "Cape Verde": { flag: "🇨🇻", code: "CV" },
  "Cayman Islands": { flag: "🇰🇾", code: "KY" },
  "Central African Republic": { flag: "🇨🇫", code: "CF" },
  Chad: { flag: "🇹🇩", code: "TD" },
  Chile: { flag: "🇨🇱", code: "CL" },
  China: { flag: "🇨🇳", code: "CN" },
  "Christmas Island": { flag: "🇨🇽", code: "CX" },
  "Cocos Islands": { flag: "🇨🇨", code: "CC" },
  Colombia: { flag: "🇨🇴", code: "CO" },
  Comoros: { flag: "🇰🇲", code: "KM" },
  Congo: { flag: "🇨🇬", code: "CG" },
  "Democratic Republic of the Congo": { flag: "🇨🇩", code: "CD" },
  "Cook Islands": { flag: "🇨🇰", code: "CK" },
  "Costa Rica": { flag: "🇨🇷", code: "CR" },
  "Cote D'Ivoire": { flag: "🇨🇮", code: "CI" },
  Croatia: { flag: "🇭🇷", code: "HR" },
  Cuba: { flag: "🇨🇺", code: "CU" },
  Cyprus: { flag: "🇨🇾", code: "CY" },
  "Czech Republic": { flag: "🇨🇿", code: "CZ" },
  Denmark: { flag: "🇩🇰", code: "DK" },
  Djibouti: { flag: "🇩🇯", code: "DJ" },
  Dominica: { flag: "🇩🇲", code: "DM" },
  "Dominican Republic": { flag: "🇩🇴", code: "DO" },
  "East Timor": { flag: "🇹🇱", code: "TL" },
  Ecuador: { flag: "🇪🇨", code: "EC" },
  Egypt: { flag: "🇪🇬", code: "EG" },
  "El Salvador": { flag: "🇸🇻", code: "SV" },
  "Equatorial Guinea": { flag: "🇬🇶", code: "GQ" },
  Eritrea: { flag: "🇪🇷", code: "ER" },
  Estonia: { flag: "🇪🇪", code: "EE" },
  Ethiopia: { flag: "🇪🇹", code: "ET" },
  "Falkland Islands": { flag: "🇫🇰", code: "FK" },
  "Faroe Islands": { flag: "🇫🇴", code: "FO" },
  Fiji: { flag: "🇫🇯", code: "FJ" },
  Finland: { flag: "🇫🇮", code: "FI" },
  France: { flag: "🇫🇷", code: "FR" },
  "French Guiana": { flag: "🇬🇫", code: "GF" },
  "French Polynesia": { flag: "🇵🇫", code: "PF" },
  Gabon: { flag: "🇬🇦", code: "GA" },
  Gambia: { flag: "🇬🇲", code: "GM" },
  Georgia: { flag: "🇬🇪", code: "GE" },
  Germany: { flag: "🇩🇪", code: "DE" },
  Ghana: { flag: "🇬🇭", code: "GH" },
  Gibraltar: { flag: "🇬🇮", code: "GI" },
  Greece: { flag: "🇬🇷", code: "GR" },
  Greenland: { flag: "🇬🇱", code: "GL" },
  Grenada: { flag: "🇬🇩", code: "GD" },
  Guadeloupe: { flag: "🇬🇵", code: "GP" },
  Guam: { flag: "🇬🇺", code: "GU" },
  Guatemala: { flag: "🇬🇹", code: "GT" },
  Guinea: { flag: "🇬🇳", code: "GN" },
  "Guinea-Bissau": { flag: "🇬🇼", code: "GW" },
  Guyana: { flag: "🇬🇾", code: "GY" },
  Haiti: { flag: "🇭🇹", code: "HT" },
  Honduras: { flag: "🇭🇳", code: "HN" },
  "Hong Kong": { flag: "🇭🇰", code: "HK" },
  Hungary: { flag: "🇭🇺", code: "HU" },
  Iceland: { flag: "🇮🇸", code: "IS" },
  India: { flag: "🇮🇳", code: "IN" },
  Indonesia: { flag: "🇮🇩", code: "ID" },
  Iran: { flag: "🇮🇷", code: "IR" },
  Iraq: { flag: "🇮🇶", code: "IQ" },
  Ireland: { flag: "🇮🇪", code: "IE" },
  Israel: { flag: "🇮🇱", code: "IL" },
  Italy: { flag: "🇮🇹", code: "IT" },
  Jamaica: { flag: "🇯🇲", code: "JM" },
  Japan: { flag: "🇯🇵", code: "JP" },
  Jordan: { flag: "🇯🇴", code: "JO" },
  Kazakhstan: { flag: "🇰🇿", code: "KZ" },
  Kenya: { flag: "🇰🇪", code: "KE" },
  Kiribati: { flag: "🇰🇮", code: "KI" },
  "North Korea": { flag: "🇰🇵", code: "KP" },
  "South Korea": { flag: "🇰🇷", code: "KR" },
  Kuwait: { flag: "🇰🇼", code: "KW" },
  Kyrgyzstan: { flag: "🇰🇬", code: "KG" },
  Laos: { flag: "🇱🇦", code: "LA" },
  Latvia: { flag: "🇱🇻", code: "LV" },
  Lebanon: { flag: "🇱🇧", code: "LB" },
  Lesotho: { flag: "🇱🇸", code: "LS" },
  Liberia: { flag: "🇱🇷", code: "LR" },
  Libya: { flag: "🇱🇾", code: "LY" },
  Liechtenstein: { flag: "🇱🇮", code: "LI" },
  Lithuania: { flag: "🇱🇹", code: "LT" },
  Luxembourg: { flag: "🇱🇺", code: "LU" },
  Macau: { flag: "🇲🇴", code: "MO" },
  Macedonia: { flag: "🇲🇰", code: "MK" },
  Madagascar: { flag: "🇲🇬", code: "MG" },
  Malawi: { flag: "🇲🇼", code: "MW" },
  Malaysia: { flag: "🇲🇾", code: "MY" },
  Maldives: { flag: "🇲🇻", code: "MV" },
  Mali: { flag: "🇲🇱", code: "ML" },
  Malta: { flag: "🇲🇹", code: "MT" },
  "Marshall Islands": { flag: "🇲🇭", code: "MH" },
  Martinique: { flag: "🇲🇶", code: "MQ" },
  Mauritania: { flag: "🇲🇷", code: "MR" },
  Mauritius: { flag: "🇲🇺", code: "MU" },
  Mexico: { flag: "🇲🇽", code: "MX" },
  Micronesia: { flag: "🇫🇲", code: "FM" },
  Moldova: { flag: "🇲🇩", code: "MD" },
  Monaco: { flag: "🇲🇨", code: "MC" },
  Mongolia: { flag: "🇲🇳", code: "MN" },
  Montenegro: { flag: "🇲🇪", code: "ME" },
  Montserrat: { flag: "🇲🇸", code: "MS" },
  Morocco: { flag: "🇲🇦", code: "MA" },
  Mozambique: { flag: "🇲🇿", code: "MZ" },
  Myanmar: { flag: "🇲🇲", code: "MM" },
  Namibia: { flag: "🇳🇦", code: "NA" },
  Nauru: { flag: "🇳🇷", code: "NR" },
  Nepal: { flag: "🇳🇵", code: "NP" },
  Netherlands: { flag: "🇳🇱", code: "NL" },
  "Netherlands Antilles": { flag: "🇦🇳", code: "AN" },
  "New Caledonia": { flag: "🇳🇨", code: "NC" },
  "New Zealand": { flag: "🇳🇿", code: "NZ" },
  Nicaragua: { flag: "🇳🇮", code: "NI" },
  Niger: { flag: "🇳🇪", code: "NE" },
  Nigeria: { flag: "🇳🇬", code: "NG" },
  Niue: { flag: "🇳🇺", code: "NU" },
  "Norfolk Island": { flag: "🇳🇫", code: "NF" },
  "Northern Mariana Islands": { flag: "🇲🇵", code: "MP" },
  Norway: { flag: "🇳🇴", code: "NO" },
  Oman: { flag: "🇴🇲", code: "OM" },
  Pakistan: { flag: "🇵🇰", code: "PK" },
  Palau: { flag: "🇵🇼", code: "PW" },
  Palestine: { flag: "🇵🇸", code: "PS" },
  Panama: { flag: "🇵🇦", code: "PA" },
  "Papua New Guinea": { flag: "🇵🇬", code: "PG" },
  Paraguay: { flag: "🇵🇾", code: "PY" },
  Peru: { flag: "🇵🇪", code: "PE" },
  Philippines: { flag: "🇵🇭", code: "PH" },
  Poland: { flag: "🇵🇱", code: "PL" },
  Portugal: { flag: "🇵🇹", code: "PT" },
  "Puerto Rico": { flag: "🇵🇷", code: "PR" },
  Qatar: { flag: "🇶🇦", code: "QA" },
  Reunion: { flag: "🇷🇪", code: "RE" },
  Romania: { flag: "🇷🇴", code: "RO" },
  Russia: { flag: "🇷🇺", code: "RU" },
  Rwanda: { flag: "🇷🇼", code: "RW" },
  "Saint Kitts and Nevis": { flag: "🇰🇳", code: "KN" },
  "Saint Lucia": { flag: "🇱🇨", code: "LC" },
  "Saint Vincent and the Grenadines": { flag: "🇻🇨", code: "VC" },
  Samoa: { flag: "🇼🇸", code: "WS" },
  "San Marino": { flag: "🇸🇲", code: "SM" },
  "Sao Tome and Principe": { flag: "🇸🇹", code: "ST" },
  "Saudi Arabia": { flag: "🇸🇦", code: "SA" },
  Senegal: { flag: "🇸🇳", code: "SN" },
  Serbia: { flag: "🇷🇸", code: "RS" },
  Seychelles: { flag: "🇸🇨", code: "SC" },
  "Sierra Leone": { flag: "🇸🇱", code: "SL" },
  Singapore: { flag: "🇸🇬", code: "SG" },
  Slovakia: { flag: "🇸🇰", code: "SK" },
  Slovenia: { flag: "🇸🇮", code: "SI" },
  "Solomon Islands": { flag: "🇸🇧", code: "SB" },
  Somalia: { flag: "🇸🇴", code: "SO" },
  "South Africa": { flag: "🇿🇦", code: "ZA" },
  Spain: { flag: "🇪🇸", code: "ES" },
  "Sri Lanka": { flag: "🇱🇰", code: "LK" },
  Sudan: { flag: "🇸🇩", code: "SD" },
  Suriname: { flag: "🇸🇷", code: "SR" },
  Swaziland: { flag: "🇸🇿", code: "SZ" },
  Sweden: { flag: "🇸🇪", code: "SE" },
  Switzerland: { flag: "🇨🇭", code: "CH" },
  Syria: { flag: "🇸🇾", code: "SY" },
  Taiwan: { flag: "🇹🇼", code: "TW" },
  Tajikistan: { flag: "🇹🇯", code: "TJ" },
  Tanzania: { flag: "🇹🇿", code: "TZ" },
  Thailand: { flag: "🇹🇭", code: "TH" },
  Togo: { flag: "🇹🇬", code: "TG" },
  Tonga: { flag: "🇹🇴", code: "TO" },
  "Trinidad and Tobago": { flag: "🇹🇹", code: "TT" },
  Tunisia: { flag: "🇹🇳", code: "TN" },
  Turkey: { flag: "🇹🇷", code: "TR" },
  Turkmenistan: { flag: "🇹🇲", code: "TM" },
  "Turks and Caicos Islands": { flag: "🇹🇨", code: "TC" },
  Tuvalu: { flag: "🇹🇻", code: "TV" },
  Uganda: { flag: "🇺🇬", code: "UG" },
  Ukraine: { flag: "🇺🇦", code: "UA" },
  "United Arab Emirates": { flag: "🇦🇪", code: "AE" },
  "United Kingdom": { flag: "🇬🇧", code: "GB" },
  "United States": { flag: "🇺🇸", code: "US" },
  Uruguay: { flag: "🇺🇾", code: "UY" },
  Uzbekistan: { flag: "🇺🇿", code: "UZ" },
  Vanuatu: { flag: "🇻🇺", code: "VU" },
  Vatican: { flag: "🇻🇦", code: "VA" },
  Venezuela: { flag: "🇻🇪", code: "VE" },
  Vietnam: { flag: "🇻🇳", code: "VN" },
  "Virgin Islands, British": { flag: "🇻🇬", code: "VG" },
  "Virgin Islands, US": { flag: "🇻🇮", code: "VI" },
  "Western Sahara": { flag: "🇪🇭", code: "EH" },
  Yemen: { flag: "🇾🇪", code: "YE" },
  Zambia: { flag: "🇿🇲", code: "ZM" },
  Zimbabwe: { flag: "🇿🇼", code: "ZW" },
};

export const getCountryFlag = (country: string): string => {
  return countryFlags[country]?.flag || "🌐";
};

export const getCountryCode = (country: string): string => {
  return countryFlags[country]?.code || "";
};

export const getCountryByCode = (code: string): string => {
  const entry = Object.entries(countryFlags).find(
    ([_, data]) => data.code === code,
  );
  return entry ? entry[0] : "";
};

export const getCountryList = (): string[] => {
  return Object.keys(countryFlags).sort();
};

export default countryFlags;
